# THIS PLAYBOOK
# - stops all currently running nodes (YOU WILL GET KICKED)
# - UPGRADES THE OS
# - (re)installs lit-os (as if from scratch)
# MANUALLY REBOOT THE MACHINE to finalize the update

- name: Update/Upgrade Debian, deploy/upgrade lit-os
  hosts: all
  become: yes
  gather_facts: true

  pre_tasks:
    - name: Print Kernel Version
      debug:
        msg: "Kernel Version is {{ ansible_kernel }}"
    - name: Print OS Version
      debug:
        msg: "OS Version is {{ ansible_distribution }} {{ ansible_distribution_version }}"    
    - name: Print network info before upgrade
      block:
        - name: Read the /etc/network/interfaces file
          command: cat /etc/network/interfaces
          ignore_errors: yes
        - name: Run ip route command
          shell: ip route
          register: ip_route_output
        - name: Print ip route output
          debug:
            var: ip_route_output.stdout
        - name: Run ip a command
          shell: ip a
          register: ip_a_output
        - name: Print ip a output
          debug:
            var: ip_a_output.stdout
        - name: Print network devices starting with 'en'
          debug:
            msg: "{{ ansible_facts['interfaces']| select('match', '^en.*') | list }}"

    - name: run pre-deploy checks
      include_tasks: tasks/prechecks.yml

  tasks:
    - name: set internal variables
      include_tasks: tasks/set_vars.yml

    - name: Stop running nodes
      include_tasks: tasks/stop_all_instances.yml

    - name: Write salt files
      include_tasks: tasks/write_salt_files.yml

    - name: Upgrade Debian packages
      include_tasks: tasks/upgrade_debian.yml

    - name: Upgrade Litos packages
      include_tasks: tasks/install_litos.yml

    - name: set boot order (boot debian first)
      include_tasks: tasks/set_boot_order.yml

  post_tasks:
    - name: Print network info after upgrade
      block:
        - name: Read the /etc/network/interfaces file
          command: grep 'bond-slaves' /etc/network/interfaces
          register: grep_interfaces_post
          changed_when: false
          when: 'provider_class is defined and provider_class == "advance"'
        - name: Check status of systemd-networkd service
          command: systemctl status systemd-networkd
          register: networkd_status
          failed_when: false
          changed_when: false
        - name: Print status of systemd-networkd service
          debug:
            msg: "systemd-networkd status: {{ networkd_status.stdout }}"
        - name: Check status of networking service
          command: systemctl status networking
          register: networking_status
          failed_when: false
          changed_when: false
        - name: Print status of networking service
          debug:
            msg: "networking status: {{ networking_status.stdout }}"
    - name: Print Kernel Version
      debug:
        msg: "Kernel Version is {{ ansible_kernel }}"
    - name: Print OS Version
      debug:
        msg: "OS Version is {{ ansible_distribution }} {{ ansible_distribution_version }}"
    - name: Get network interfaces
      shell: ip a | grep '^[0-9]*:' | cut -d':' -f2 --output-delimiter=":"
      register: ip_a_output
      changed_when: false
    - name: Print network interfaces
      debug:
        var: ip_a_output.stdout
    - name: COMPARE MANUALLY !!! - interfaces post-update (it should show interfaces that match the output of "Print network interfaces" above, ask the team if it doesnt and DO NOT REBOOT)
      debug:
        msg: "{{ grep_interfaces_post.stdout_lines }}"
      when: 'provider_class is defined and provider_class == "advance"'
      changed_when: true # Make yellow to warn this is a manual step
    - name: OVH/ADVANCE **MANUAL** STEP - Enable OLA (if fresh install)!!
      debug:
        msg: "Follow the testnet guide https://www.notion.so/litprotocol/Datil-test-Testnet-Node-Provisioning-Guide-6c78bd5e7ebd4b0f8cec1ad78e130be2?pvs=4#22de9bba0e7e49108509a5d60b8f6aaa for info on how"
      when: 'provider_class is defined and provider_class == "advance"'
      changed_when: true # Make yellow to warn this is a manual step