---
- name: Check if vars have been provided
  ansible.builtin.assert:
    that:
      - tar_decrypt is defined and tar_decrypt | length > 0
      - network_name is defined and network_name in ["naga_test", "datil_test", "datil", "datil_clone", "custom"]
      - network_name != "custom" or (
          branch_os is defined and branch_os | length > 0 and
          branch_assets is defined and branch_assets | length > 0 and
          subnet_id is defined and subnet_id | length > 0
        )
      - root_email is defined and root_email | length > 0
      - ssh_user is defined and ssh_user | length > 0
      - ssh_public_key is defined and ssh_public_key | length > 0
      - provider is defined and provider | length > 0
      # - (provider == 'ovh' and provider_class in ["advance", "scale"]) or provider_class == ""
      - ansible_host is defined and ansible_host | length > 0
      - host_ip is defined and host_ip | length > 0
      - host_gw is defined and host_gw | length > 0
      - guest_ip is defined and guest_ip | length > 0
      - guest_gw is defined and guest_gw | length > 0
    fail_msg: "Error: Some required information was not provided, please revisit machine-description.yml"

- name: Delete old vector repo # this breaks apt-update if it's still on the system as the repo no longer exists
  file:
    path: /etc/apt/sources.list.d/timber-vector.list
    state: absent

# TODO/RAD: DELL 7525 doesnt have a BIOS release yet, disabling BIOS upgrade enforcement
# - name: Ensure dmidecode is installed
#   apt:
#     name: dmidecode
#     state: present
#     update_cache: yes
# - name: Get BIOS Revision
#   become: true
#   command: dmidecode -t bios
#   register: bios_revision
# - name: Extract BIOS Revision
#   set_fact:
#     bios_revision_line: "{{ bios_revision.stdout_lines | select('search', 'BIOS Revision') | regex_search('([0-9.]+)') }}"
#     bios_vendor_line: "{{ bios_revision.stdout_lines | select('search', 'Vendor') | map('trim') | join('') }}"
# - name: Fail if outdated BIOS (OVH / Tyan)
#   fail:
#     msg: "Your BIOS is v{{ bios_revision_line }}. Please manually upgrade your OVH machine's BIOS to 5.22 or newer (see guide)"
#   when: "'ovh' in provider and bios_revision_line is version('5.22', '<')"
# - name: Fail if outdated BIOS (leaseweb / DELL)
#   fail:
#     msg: "Your BIOS is v{{ bios_revision_line }}. Please manually upgrade your leaseweb machine's BIOS to 2.16 or newer (see guide)"
#   when: "'leaseweb' in provider and bios_revision_line is version('2.16', '<')"
# - name: MANUALLY check if BIOS update is needed (other vendors)
#   debug:
#     msg: "Your BIOS is v{{ bios_revision_line }}. We cannot automatically verify your BIOS, please ENSURE that you have a BIOS with the most recent AMD AGESA available installed"
#   when: "provider not in ['leaseweb','ovh']"
#   changed_when: true