- name: Ensure network_name is provided
  fail:
    msg: "The required variable 'network_name' is not provided."
  when: network_name is not defined
- name: Check if network_name is valid
  fail:
    msg: "Invalid network_name provided. The network_name must be 'datil', 'datil_test', 'datil_clone', or 'custom'."
  when: network_name not in ['datil', 'datil_test', 'datil_clone', 'custom']
- name: Set variables based on network_name
  when: network_name != 'custom'
  block:
    - name: Set subnet_id based on network_name
      set_fact:
        subnet_id: "{{ '21d636d95eE71150c0c3Ffa79268c989a329d1CE' if network_name == 'datil' else '5758aDa5a1dC05e659eF0B5062fbcF093Ec572D1' if network_name == 'datil_clone' else 'dec37933239846834b3BfD408913Ed3dbEf6588F' if network_name == 'datil_test' }}"

    - name: Set env based on network_name
      set_fact:
        env: "{{ 'prod' if network_name == 'datil' or network_name == 'datil_clone' else 'dev' if network_name == 'datil_test' }}"

    - name: Set lit-assets branch
      set_fact:
        branch_assets: "{{ 'release-datil-prod-2024-10-22' if network_name == 'datil' or network_name == 'datil_clone' else 'release-datil-test-2025-02-25' if network_name == 'datil_test' }}"

    - name: Set lit-os branch
      set_fact:
        branch_os: "{{ 'release-datil-prod-2024-10-30' if network_name == 'datil' or network_name == 'datil_clone' else 'release-datil-test-2025-02-25' if network_name == 'datil_test' }}"
