---
- name: Check if networking service exists and is enabled (so it can launch on reboot)
  command: systemctl is-enabled networking

- name: Check if systemd-networkd exists
  command: systemctl list-unit-files systemd-networkd.service
  register: networkd_exists
  ignore_errors: true

- name: Mask and stop systemd-networkd service
  systemd:
    name: systemd-networkd
    state: stopped
    enabled: false
    masked: true
  when: networkd_exists is success and 'systemd-networkd.service' in networkd_exists.stdout
  register: stop_networkd
  retries: 2
  delay: 30
  notify: notify reboot needed
