---
- name: Delete old vector repo
  file:
    path: /etc/apt/sources.list.d/timber-vector.list
    state: absent
    
- name: Update apt repository cache
  apt:
    update_cache: yes

- name: Upgrade all packages to the latest version
  apt:
    upgrade: safe
  register: upgrade_result
  until: upgrade_result is succeeded
  retries: 5
  delay: 30

- name: Replace 'bullseye' with 'bookworm' in /etc/apt/sources.list
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: 'bullseye'
    replace: 'bookworm'
    backup: no

- name: Update apt repository cache after modifying sources.list
  apt:
    update_cache: yes

- name: Perform distribution upgrade
  apt:
    upgrade: dist
  register: dist_upgrade_result
  until: dist_upgrade_result is succeeded
  retries: 5

- name: Autoremove unnecessary packages
  apt:
    autoremove: yes

- name: Run lit os update
  command: lit os update
  register: grep_output
  ignore_errors: yes # Ignore because lit os might not even be installed yet

- name: Print network devices starting with 'en'
  debug:
    msg: "{{ ansible_facts['interfaces']| select('match', '^en.*') | list }}"

- name: Read the /etc/network/interfaces file
  command: grep 'en' /etc/network/interfaces
  register: grep_output
  ignore_errors: yes

- name: Print grep output
  debug:
    msg: "{{ grep_output.stdout_lines }}"
